- name: Check mandatory variables are defined
  assert:
    that:
      - repository is defined

- name: Check exclude files exist (stat)
  stat:
    path: "{{ item }}"
  register: exclude_files
  with_items: "{{ excluded_pkgs_file }}"

- name: Check exclude files exist
  assert:
    that:
      - "{{ item.stat.exists }}"
  with_items: "{{ exclude_files.results }}"

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ prerequisites[(ansible_os_family | lower)] }}"

- name: Load debian-specific configuration
  include: debian.yml
  when: ansible_os_family == 'Debian'

- name: Load RHEL-specific configuration
  include: redhat.yml
  when: ansible_os_family == 'RedHat'
