---
- set_fact:
    all_pkgs_file: "{{ installed_pkgs_file | dirname }}/all.pkgs"

- name: Concatenate the repository list
  set_fact:
    yum_enablerepo_str: "--enablerepo={{ repository | join(' --enablerepo=') }}"

- name: Get all the packages from UMD/CMD repositories
  shell: "/usr/bin/repoquery --qf=\"%{name}\" --disablerepo=* {{ yum_enablerepo_str }} -a"
  register: pkglist

- name: Save package list in file before adding further modifications
  copy: 
    content: "{{ pkglist.stdout }}"
    dest: "{{ all_pkgs_file }}"

- name: Get unmatched list of packages
  include_tasks: unmatch_pkgs.yml
  loop: "{{ excluded_pkgs_file }}"
  loop_control:
    loop_var: excluded_pkgs_file_item
    
- name: Save resultant package list in installed_pkgs_file
  copy: 
    src: "{{ all_pkgs_file }}"
    dest: "{{ installed_pkgs_file }}"

- name: Install all the packages
  shell: "yum -y install {{ yum_enablerepo_str }} --setopt=protected_multilib=false $(cat {{ installed_pkgs_file }})"
  args:
    warn: False
  when: (ansible_distribution == "CentOS") or (ansible_distribution == "Scientific") and (ansible_distribution_major_version == "6")

- name: Install all the packages
  shell: "yum -y install {{ yum_enablerepo_str }} $(cat {{ installed_pkgs_file }})"
  args:
    warn: False
  when: (ansible_distribution == "CentOS") and (ansible_distribution_major_version == "7")
